# Generated by Django 5.2.5 on 2026-05-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ats_score", models.IntegerField(default=0)),
                ("skills_found", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
    ]
