# Generated by Django 5.2.5 on 2026-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="match_score",
            field=models.IntegerField(default=0),
        ),
    ]
