# Generated by Django 5.2.5 on 2026-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_analysis_match_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="semantic_score",
            field=models.FloatField(default=0),
        ),
    ]
